### ISSUE TITLE
dothill-provisioner 2.4.0 : resize failing

### ISSUE THREAD

**Issue by abuisine** [enix/dothill-csi#81]
I first thought that we had a problem on the controller as I got :
```
Warning  ExternalExpanding         13s                 volume_expand                                                                                        Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
Normal   Resizing                  13s                 external-resizer dothill.csi.enix.io                                                                 External resizer is resizing volume pvc-fbbe7240-b2a2-4ebb-8aa6-54fb30bd7c06
Normal   FileSystemResizeRequired  12s                 external-resizer dothill.csi.enix.io                                                                 Require file system resize of volume on node
  ```
but if finally went through and gave the order to the node to resize,
at the end it failed with the multipath sidecar complaining about not begin able to access sysfs with : ```couldn't get size for sysfs. cannot resize```

**Comment by plaffitt** [comment]
I figured out that this issue is caused by multipathd not being able to load mapping tables on startup, caused by `/run/udev` directory not being mounted. I will soon release a patch including this fix.

Concerning the warning `Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.`, it looks normal to me. I think it's the expected behavior when using a CSI provisionner. (plugin = flexvolume, external controller = CSI).
